services:
  backend:
    build: .
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    env_file:
      - ./config/.env
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/looprail_backend
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=looprail_backend
    command: sh -c 'if [ "$ENVIRONMENT" = "dev" ]; then uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src --log-level debug; else uv run gunicorn -c gunicorn.conf.py src.main:app; fi'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml

  worker:
    build: .
    env_file:
      - ./config/.env
    depends_on:
      - db
      - redis
    command: uv run -m src.worker
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml

  notification-worker:
    build: .
    env_file:
      - ./config/.env
    depends_on:
      - db
      - redis
    command: uv run -m services.notifications.worker
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=looprail_backend
    ports:
      - "5431:5432"

  redis:
    image: redis:6

volumes:
  postgres_data:
