[[ledgers]]
name = "Customer Wallets Ledger"
ledger_id = "ldg_68fc96d5-1c2c-4204-91a5-e6a0cb3a9c58" # TODO load from .env
meta_data = { description = "Ledger for managing customer wallets", application = "Wallet Management System" }

