[[ledgers]]
name = "Customer Wallets Ledger"
ledger_id = "ldg_073f7ffe-9dfd-42ce-aa50-d1dca1788adc" # TODO load from .env
api_key = "CUSTOMER_WALLETS_LEDGER_API_KEY" # TODO load from .env
meta_data = { description = "Ledger for managing customer wallets", application = "Wallet Management System" }

